services:
  frontend:
    build:
      context: .
      target: dev
    container_name: project-intern-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - WATCHPACK_POLLING=true
      - VITE_API_TARGET=http://backend:8000
