version: '3.8'

services:
  frontend:
    build:
      context: .
      target: dev
    container_name: project-intern-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
