# Generated by Django 6.0.7 on 2026-07-21 08:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('description', models.CharField()),
                ('cadence', models.CharField(choices=[('Daily', 'daily'), ('Weekly', 'weekly'), ('Custom', 'n_times_per_week')], default='daily')),
                ('target_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('archived_at', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Goals',
            },
        ),
        migrations.CreateModel(
            name='StreakState',
            fields=[
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='goals.goal')),
                ('current_streak', models.IntegerField()),
                ('longest_streak', models.IntegerField()),
                ('last_checkin', models.DateField(null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('at-risk', 'at-risk'), ('broken', 'broken')], default='active')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Streak',
            },
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user'], name='Goals_user_id_3f81a0_idx'),
        ),
    ]
