# Generated by Django 6.0.7 on 2026-07-21 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_alter_goal_cadence_alter_goal_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='goal',
            name='Goals_user_id_3f81a0_idx',
        ),
        migrations.AlterField(
            model_name='goal',
            name='archived_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='cadence',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('n_times_per_week', 'Custom')], default='daily', max_length=50),
        ),
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='streakstate',
            name='goal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='streak', serialize=False, to='goals.goal'),
        ),
        migrations.AlterField(
            model_name='streakstate',
            name='last_checkin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='streakstate',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('at-risk', 'at-risk'), ('broken', 'broken')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='streakstate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'is_active'], name='Goals_user_id_9bf2dc_idx'),
        ),
    ]
