# Generated by Django 6.0.7 on 2026-08-06 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0003_remove_goal_goals_user_id_3f81a0_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, max_length=250)),
                ('image', models.ImageField(null=True, upload_to='posts/')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='goals.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Posts',
                'ordering': ['-posted_at'],
                'indexes': [models.Index(fields=['user', 'posted_at'], name='Posts_user_id_760857_idx'), models.Index(fields=['goal'], name='Posts_goal_id_144352_idx')],
            },
        ),
    ]
