# Generated by Django 6.0.7 on 2026-08-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_follow_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='follow',
            name='posts_follo_followe_5565c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='follow',
            name='posts_follo_followi_6451f9_idx',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
